# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='sqs_message_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
