engines:
  radon:
    enabled: true
  pep8:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python:
ratings:
  paths:
    - "**.py"
exclude_paths:
- "**/tests/"
- "**/migrations/"
- "README.md"
- "LICENCE"
- "*.yml"
- "**/conftest.py"
- "**/*.html"
- "**/admin.py"
