[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git         # exclude a few common directories in the
    | \.circleci          # root of the project
    | \__pycache__
    | \.pytest_cache
    | \.venv
    | \.vscode
    | node_modules
    | venv
  )/
  | manage.py       # also separately exclude a file in the root of the project
)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
