# Generated by Django 4.2.17 on 2025-03-19 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField()),
                ('name', models.CharField()),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('4', 'region'),
                            ('3', 'combined authority'),
                            ('2', 'county'),
                            ('1', 'local authority district'),
                        ],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('email', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField()),
                ('postcode', models.CharField()),
                ('latitude', models.CharField()),
                ('longitude', models.CharField()),
                ('northings', models.CharField()),
                ('eastings', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='GrowthHub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('boundaries', models.ManyToManyField(to='dataservices.boundary')),
                (
                    'contacts',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataservices.contactcard'),
                ),
                (
                    'place',
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataservices.place'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ChamberOfCommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                (
                    'contacts',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataservices.contactcard'),
                ),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataservices.place')),
            ],
        ),
    ]
