# Generated by Django 4.2.17 on 2025-03-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0002_boundary_contactcard_place_growthhub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='code',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='chamberofcommerce',
            name='contacts',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataservices.contactcard'
            ),
        ),
        migrations.AlterField(
            model_name='growthhub',
            name='contacts',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataservices.contactcard'
            ),
        ),
        migrations.AlterField(
            model_name='growthhub',
            name='name',
            field=models.CharField(unique=True),
        ),
    ]
