# Generated by Django 2.2.10 on 2020-05-22 09:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0002_corruptionperceptionsindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataServicesCacheLoad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('class_name', models.CharField(max_length=50)),
                ('function_parameters', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('function_name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
