# Generated by Django 4.2.19 on 2025-04-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ('dataservices', '0004_website_remove_growthhub_description_and_more'),
        ('dataservices', '0005_remove_contactcard_contact_form_and_more'),
    ]

    dependencies = [
        ('dataservices', '0003_alter_boundary_code_alter_chamberofcommerce_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='growthhub',
            name='description',
        ),
        migrations.AddField(
            model_name='chamberofcommerce',
            name='digest',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthhub',
            name='digest',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='type',
            field=models.CharField(
                choices=[
                    ('5', 'country'),
                    ('4', 'region'),
                    ('3', 'combined authority'),
                    ('2', 'county'),
                    ('1', 'local authority district'),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='chamberofcommerce',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='website',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataservices.website'
            ),
        ),
        migrations.RenameModel(
            old_name='GrowthHub',
            new_name='SupportHub',
        ),
        migrations.AddField(
            model_name='contactcard',
            name='contact_form_label',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='contact_form_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='website_label',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
