# Generated by Django 2.2.10 on 2020-06-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0003_cia_factbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciafactbook',
            options={'verbose_name': 'CIA Factbook'},
        ),
    ]
