# Generated by Django 4.2.17 on 2025-04-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0003_alter_boundary_code_alter_chamberofcommerce_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='growthhub',
            name='description',
        ),
        migrations.AddField(
            model_name='chamberofcommerce',
            name='digest',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthhub',
            name='digest',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='type',
            field=models.CharField(
                choices=[
                    ('5', 'country'),
                    ('4', 'region'),
                    ('3', 'combined authority'),
                    ('2', 'county'),
                    ('1', 'local authority district'),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='chamberofcommerce',
            name='name',
            field=models.CharField(unique=True),
        ),
        migrations.RenameModel(
            old_name='GrowthHub',
            new_name='SupportHub',
        ),
    ]
