# Generated by Django 2.2.13 on 2020-07-01 09:14

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0004_auto_20200619_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldEconomicOutlook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('country_code', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('scale', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=50)),
                ('year_2020', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('year_2021', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
