# Generated by Django 4.2.17 on 2025-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0004_website_remove_growthhub_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcard',
            name='contact_form_label',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='contact_form_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactcard',
            name='website_label',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
