# Generated by Django 2.2.13 on 2020-07-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0005_worldeconomicoutlook'),
        ('dataservices', '0004_auto_20200625_2000'),
    ]

    operations = [
    ]
