# Generated by Django 4.2.19 on 2025-04-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0005_remove_contactcard_contact_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamberofcommerce',
            name='boundary',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataservices.boundary'
            ),
        ),
    ]
