# Generated by Django 2.2.13 on 2020-07-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0005_worldeconomicoutlook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciafactbook',
            old_name='country_key',
            new_name='country_code',
        ),
    ]
