# Generated by Django 4.2.19 on 2025-05-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0006_chamberofcommerce_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='postcode',
            field=models.CharField(blank=True, null=True),
        ),
    ]
