# Generated by Django 2.2.13 on 2020-10-21 08:23

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0008_consumerpriceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('iso1', models.CharField(max_length=10, unique=True)),
                ('iso2', models.CharField(max_length=10, unique=True)),
                ('iso3', models.CharField(max_length=10, unique=True)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
