# Generated by Django 2.2.13 on 2020-11-25 11:32

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0009_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPPerCapita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=50)),
                ('year_2019', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
