# Generated by Django 2.2.13 on 2020-11-30 12:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0010_gdppercapita'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('hs_code', models.PositiveIntegerField(verbose_name='HS Code')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Suggested Countries')),
            ],
            options={
                'verbose_name': 'Suggested Country',
                'verbose_name_plural': 'Suggested Countries',
            },
        ),
    ]
