# Generated by Django 2.2.13 on 2021-01-14 16:42

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0020_ruleoflaw'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('country_name', models.CharField(max_length=255)),
                ('iso2', models.CharField(max_length=50)),
                ('currency_name', models.CharField(max_length=50)),
                ('alphabetic_code', models.CharField(blank=True, max_length=50, null=True)),
                ('numeric_code', models.IntegerField(blank=True, null=True)),
                ('minor_unit', models.CharField(blank=True, max_length=50, null=True)),
                (
                    'country',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dataservices.Country',
                        verbose_name='Countries',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Currencies',
            },
        ),
    ]
