# Generated by Django 2.2.13 on 2021-01-29 17:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0021_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingBlocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('membership_code', models.CharField(max_length=255)),
                ('iso2', models.CharField(max_length=50)),
                ('country_territory_name', models.CharField(blank=True, max_length=255, null=True)),
                ('trading_bloc_code', models.CharField(max_length=255)),
                ('trading_bloc_name', models.CharField(max_length=255)),
                ('membership_start_date', models.DateField(blank=True, null=True)),
                ('membership_end_date', models.DateField(blank=True, null=True)),
                (
                    'country',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dataservices.Country',
                        verbose_name='Countries',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Trading Blocs',
            },
        ),
    ]
