# Generated by Django 2.2.13 on 2021-02-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0022_tradingblocs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingblocs',
            options={'verbose_name': 'Trading Bloc'},
        ),
    ]
