# Generated by Django 2.2.13 on 2021-02-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0023_auto_20210204_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComtradeReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('classification', models.CharField(max_length=3)),
                ('country_iso3', models.CharField(max_length=3)),
                ('uk_or_world', models.CharField(max_length=3)),
                ('commodity_code', models.CharField(max_length=6)),
                ('trade_value', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries')),
            ],
        ),
        migrations.AddIndex(
            model_name='comtradereport',
            index=models.Index(fields=['commodity_code', 'country', 'uk_or_world'], name='dataservice_commodi_c61be8_idx'),
        ),
    ]
