# Generated by Django 2.2.13 on 2021-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0024_auto_20210219_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corruptionperceptionsindex',
            old_name='cpi_score_2019',
            new_name='cpi_score',
        ),
        migrations.AddField(
            model_name='corruptionperceptionsindex',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='corruptionperceptionsindex',
            options={},
        ),
        migrations.AlterField(
            model_name='corruptionperceptionsindex',
            name='country_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='corruptionperceptionsindex',
            name='country_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='corruptionperceptionsindex',
            unique_together={('country_code', 'year')},
        )
    ]
