# Generated by Django 2.2.13 on 2021-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0025_auto_20210219_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumerpriceindex',
            options={},
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='country_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='country_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='consumerpriceindex',
            unique_together={('country_code', 'year')},
        ),
    ]
