# Generated by Django 2.2.13 on 2021-03-05 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0026_amended_cpi_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('age_0_4', models.PositiveIntegerField(default=None, null=True)),
                ('age_5_9', models.PositiveIntegerField(default=None, null=True)),
                ('age_10_14', models.PositiveIntegerField(default=None, null=True)),
                ('age_15_19', models.PositiveIntegerField(default=None, null=True)),
                ('age_20_24', models.PositiveIntegerField(default=None, null=True)),
                ('age_25_29', models.PositiveIntegerField(default=None, null=True)),
                ('age_30_34', models.PositiveIntegerField(default=None, null=True)),
                ('age_35_39', models.PositiveIntegerField(default=None, null=True)),
                ('age_40_44', models.PositiveIntegerField(default=None, null=True)),
                ('age_45_49', models.PositiveIntegerField(default=None, null=True)),
                ('age_50_54', models.PositiveIntegerField(default=None, null=True)),
                ('age_55_59', models.PositiveIntegerField(default=None, null=True)),
                ('age_60_64', models.PositiveIntegerField(default=None, null=True)),
                ('age_65_69', models.PositiveIntegerField(default=None, null=True)),
                ('age_70_74', models.PositiveIntegerField(default=None, null=True)),
                ('age_75_79', models.PositiveIntegerField(default=None, null=True)),
                ('age_80_84', models.PositiveIntegerField(default=None, null=True)),
                ('age_85_89', models.PositiveIntegerField(default=None, null=True)),
                ('age_90_94', models.PositiveIntegerField(default=None, null=True)),
                ('age_95_99', models.PositiveIntegerField(default=None, null=True)),
                ('age_100_plus', models.PositiveIntegerField(default=None, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'Target age groups',
            },
        ),
    ]
