# Generated by Django 2.2.13 on 2021-03-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0027_populationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationUrbanRural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_rural', models.CharField(max_length=5)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country')),
            ],
            options={
                'unique_together': {('urban_rural', 'country', 'year')},
            },
        ),
    ]
