# Generated by Django 2.2.13 on 2021-04-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0028_populationurbanrural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='populationdata',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries'),
        ),
    ]
