# Generated by Django 2.2.24 on 2021-07-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0029_auto_20210406_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country | DIT DATA', 'verbose_name_plural': 'Countries | DIT DATA'},
        ),
    ]
