# Generated by Django 2.2.24 on 2021-07-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0030_auto_20210708_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciafactbook',
            options={'verbose_name': 'CIA Factbook | CIA', 'verbose_name_plural': 'CIA Factbook | CIA'},
        ),
        migrations.AlterModelOptions(
            name='consumerpriceindex',
            options={'verbose_name_plural': 'Consumer price indexes'},
        ),
        migrations.AlterModelOptions(
            name='corruptionperceptionsindex',
            options={'verbose_name_plural': 'Corruption perceptions indexes'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Currencies | ISO', 'verbose_name_plural': 'Currencies | ISO'},
        ),
        migrations.AlterModelOptions(
            name='gdppercapita',
            options={'verbose_name': 'GDP Per Capita', 'verbose_name_plural': 'GDP Per Capita'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={
                'verbose_name': 'Net Adjusted Income | World Bank',
                'verbose_name_plural': 'Net Adjusted Income | World Bank',
            },
        ),
        migrations.AlterModelOptions(
            name='internetusage',
            options={
                'verbose_name': 'Internet Usage | World Bank',
                'verbose_name_plural': 'Internet Usage | World Bank',
            },
        ),
        migrations.AlterModelOptions(
            name='ruleoflaw',
            options={
                'verbose_name': 'Rule of Law Rank | World Bank',
                'verbose_name_plural': 'Rule of Law Rank | World Bank',
            },
        ),
        migrations.AlterModelOptions(
            name='suggestedcountry',
            options={
                'verbose_name': 'Suggested Country | DIT CREST',
                'verbose_name_plural': 'Suggested Countries | DIT CREST',
            },
        ),
        migrations.AlterModelOptions(
            name='worldeconomicoutlook',
            options={
                'verbose_name': 'World Economic Outlooks | IMF',
                'verbose_name_plural': 'World Economic Outlooks | IMF',
            },
        ),
    ]
