# Generated by Django 2.2.24 on 2021-10-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0030_auto_20210708_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumerpriceindex',
            options={'verbose_name': 'Consumer price indexes | IMF', 'verbose_name_plural': 'Consumer price indexes | IMF'},
        ),
        migrations.AlterModelOptions(
            name='corruptionperceptionsindex',
            options={'verbose_name': 'Corruption perceptions indexes  | Transparency International', 'verbose_name_plural': 'Corruption perceptions indexes  | Transparency International'},
        ),
        migrations.AlterModelOptions(
            name='easeofdoingbusiness',
            options={'verbose_name': 'Ease of doing business | World Bank Doing Business', 'verbose_name_plural': 'Ease of doing business | World Bank Doing Business'},
        ),
        migrations.AlterModelOptions(
            name='gdppercapita',
            options={'verbose_name': 'GDP Per Capita | World Bank', 'verbose_name_plural': 'GDP Per Capita | World Bank'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'verbose_name': 'Annual Net Adjusted Income per Capita | World Bank', 'verbose_name_plural': 'Annual Net Adjusted Income per Capita | World Bank'},
        ),
        migrations.AlterModelOptions(
            name='populationdata',
            options={'verbose_name': 'Target age groups | UN Population division', 'verbose_name_plural': 'Target age groups | UN Population division'},
        ),
        migrations.AlterModelOptions(
            name='ruleoflaw',
            options={'verbose_name': 'Rule of Law Rank | Global Innovation Index', 'verbose_name_plural': 'Rule of Law Rank | Global Innovation Index'},
        ),
        migrations.AlterModelOptions(
            name='tradingblocs',
            options={'verbose_name': 'Trading blocs | DIT DATA', 'verbose_name_plural': 'Trading blocs | DIT DATA'},
        ),
    ]
