# Generated by Django 2.2.24 on 2021-11-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0031_auto_20211005_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
