# Generated by Django 2.2.24 on 2021-11-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0032_country_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='easeofdoingbusiness',
            old_name='year_2019',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='easeofdoingbusiness',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='easeofdoingbusiness',
            name='country_code',
        ),
        migrations.AddField(
            model_name='easeofdoingbusiness',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='easeofdoingbusiness',
            unique_together={('country', 'year')},
        ),
    ]
