# Generated by Django 2.2.24 on 2021-12-01 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0032_country_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumerpriceindex',
            unique_together={('country', 'year')},
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='country_name',
        ),
    ]
