# Generated by Django 2.2.24 on 2021-12-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0033_auto_20211201_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gdppercapita',
            old_name='year_2019',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='gdppercapita',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='gdppercapita',
            name='country_name',
        ),
        migrations.AddField(
            model_name='gdppercapita',
            name='year',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
    ]
