# Generated by Django 2.2.24 on 2021-12-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0035_auto_20211202_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='income',
            name='country_name',
        ),
    ]
