# Generated by Django 2.2.24 on 2021-12-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0036_auto_20211206_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetusage',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='internetusage',
            name='country_name',
        ),
    ]
