# Generated by Django 2.2.24 on 2021-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0037_auto_20211208_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdppercapita',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
