# Generated by Django 2.2.28 on 2022-05-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0038_auto_20211215_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKTradeInServicesByCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('service_code', models.CharField(blank=True, max_length=200, null=True)),
                ('service_name', models.CharField(blank=True, max_length=200, null=True)),
                ('imports', models.PositiveIntegerField(blank=True, null=True)),
                ('exports', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'UK trade in services by country',
            },
        ),
        migrations.CreateModel(
            name='UKTradeInGoodsByCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commodity_code', models.CharField(blank=True, max_length=10, null=True)),
                ('commodity_name', models.CharField(max_length=250)),
                ('imports', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exports', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'UK trade in goods by country',
            },
        ),
        migrations.CreateModel(
            name='UKTotalTradeByCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ons_iso_alpha_2_code', models.CharField(max_length=2)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imports', models.PositiveIntegerField(blank=True, null=True)),
                ('exports', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'UK total trade by country',
            },
        ),
    ]
