# Generated by Django 2.2.24 on 2021-12-01 17:05

import django.contrib.postgres.fields.jsonb
import django_extensions.db.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0038_auto_20211215_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComtradeReportLoadblock',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('process', models.BooleanField(default=False)),
                ('result', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataservices.Country', verbose_name='Countries')),
                ('row_count', models.IntegerField(blank=True, null=True)),
            ],
        ),

        migrations.AlterModelOptions(
            name='comtradereportloadblock',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
    ]
