# Generated by Django 2.2.27 on 2022-04-03 13:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0038_auto_20211215_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommodityExports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('commodity_code', models.CharField(blank=True, max_length=10, null=True)),
                ('commodity', models.CharField(max_length=250)),
                ('direction', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    'country',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='dataservices.Country',
                        verbose_name='Countries',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Country by commodity',
                'verbose_name_plural': 'Country by commodity',
            },
        ),
    ]
