# Generated by Django 2.2.27 on 2022-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0040_uktradeinservicebycountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityexports',
            name='root_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commodityexports',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commodityexports',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
