# Generated by Django 2.2.28 on 2022-08-15 11:34

from django.db import migrations
from dataservices.views import MetadataMixin


def seed_metadata(apps, schema_editor):
    # Seed the database with metadata records for eligible view names.
    Metadata = apps.get_model('dataservices', 'Metadata')

    views_with_metadata = [cls.__name__ for cls in MetadataMixin.__subclasses__()]

    for view_name in views_with_metadata:
        Metadata.objects.get_or_create(view_name=view_name)


def rollback(apps, schema_editor):
    Metadata = apps.get_model('dataservices', 'Metadata')

    Metadata.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0041_metadata'),
    ]

    operations = [
        migrations.RunPython(seed_metadata, rollback),
    ]
