# Generated by Django 2.2.27 on 2022-04-12 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0041_auto_20220406_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKTotalTradeByCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('direction', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=15)),
                ('type', models.CharField(choices=[('GOODS', 'Goods'), ('SERVICES', 'Services')], max_length=15)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'UK total trade by country',
            },
        ),
    ]
