# Generated by Django 2.2.27 on 2022-04-21 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0041_auto_20220406_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKTotalTradeByCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imports', models.PositiveIntegerField(blank=True, null=True)),
                ('exports', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'UK total trade by country',
            },
        ),
    ]
