# Generated by Django 2.2.28 on 2022-05-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0042_uktotaltradebycountry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodityexports',
            old_name='month',
            new_name='quarter',
        ),
    ]
