# Generated by Django 2.2.28 on 2022-05-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0042_uktotaltradebycountry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uktradeinservicebycountry',
            options={},
        ),
        migrations.RenameField(
            model_name='uktradeinservicebycountry',
            old_name='servicetype_code',
            new_name='service_code',
        ),
        migrations.RenameField(
            model_name='uktradeinservicebycountry',
            old_name='service_type',
            new_name='service_name',
        ),
        migrations.RemoveField(
            model_name='uktradeinservicebycountry',
            name='created',
        ),
        migrations.RemoveField(
            model_name='uktradeinservicebycountry',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='uktradeinservicebycountry',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='uktradeinservicebycountry',
            name='value',
        ),
        migrations.AddField(
            model_name='uktradeinservicebycountry',
            name='exports',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uktradeinservicebycountry',
            name='imports',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
