# Generated by Django 3.2.15 on 2022-10-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0042_add_metadata_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldeconomicoutlookbycountry',
            name='ons_iso_alpha_3_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
