# Generated by Django 3.2.15 on 2022-10-19 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0043_worldeconomicoutlookbycountry_ons_iso_alpha_3_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKFreeTradeAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'UK free trade aggreement',
                'verbose_name_plural': 'UK free trade aggreements',
                'ordering': ['name'],
            },
        ),
    ]
