# Generated by Django 2.2.28 on 2022-05-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0043_auto_20220518_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKTradeInGoodsByCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commodity_code', models.CharField(blank=True, max_length=10, null=True)),
                ('commodity_name', models.CharField(max_length=250)),
                ('parent_code', models.CharField(blank=True, max_length=10, null=True)),
                ('imports', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exports', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataservices.Country', verbose_name='Countries')),
            ],
            options={
                'verbose_name': 'UK trade in goods by country',
            },
        ),
        migrations.AlterModelOptions(
            name='uktradeinservicebycountry',
            options={'verbose_name': 'UK trade in services by country'},
        ),
        migrations.AlterField(
            model_name='uktradeinservicebycountry',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CommodityExports',
        ),
    ]
