# Generated by Django 4.2.11 on 2024-04-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0046_alter_ciafactbook_factbook_data_alter_metadata_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EYBBusinessClusterInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_description', models.CharField()),
                ('geo_code', models.CharField()),
                ('sic_code', models.CharField()),
                ('total_business_count', models.IntegerField(blank=True, null=True)),
                ('business_count_release_year', models.SmallIntegerField(blank=True, null=True)),
                ('total_employee_count', models.IntegerField(blank=True, null=True)),
                ('employee_count_release_year', models.SmallIntegerField(blank=True, null=True)),
                ('dbt_full_sector_name', models.CharField(blank=True, null=True)),
                ('dbt_sector_name', models.CharField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Business Cluster Information for a geographic/standard industrial classification code combination',
                'ordering': ['-business_count_release_year', '-employee_count_release_year'],
            },
        ),
    ]
