# Generated by Django 4.2.11 on 2024-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0047_eybbusinessclusterinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='eybbusinessclusterinformation',
            name='sic_description',
            field=models.CharField(default=None),
            preserve_default=False,
        ),
    ]
