# Generated by Django 4.2.11 on 2024-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0048_eybbusinessclusterinformation_sic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(unique=True)),
                ('name', models.CharField(unique=True)),
                ('type', models.CharField(choices=[('Country', 'Country'), ('Territory', 'Territory')])),
                ('iso1_code', models.CharField(blank=True, null=True, unique=True)),
                ('iso2_code', models.CharField(blank=True, null=True, unique=True)),
                ('iso3_code', models.CharField(blank=True, null=True, unique=True)),
                ('overseas_region_overseas_region_name', models.CharField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('region', models.CharField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Market | Data Workspace',
                'verbose_name_plural': 'Markets | Data Workspace',
            },
        ),
    ]
