# Generated by Django 4.2.11 on 2024-05-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0050_eybstatistacommercialpropertyrent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EYBSalaryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_description', models.CharField()),
                ('vertical', models.CharField()),
                ('professional_level', models.CharField()),
                ('median_salary', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('mean_salary', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dataworkspace_ingestion_year', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='EYBStatistaCommercialPropertyRent',
            new_name='EYBCommercialPropertyRent',
        ),
    ]
