# Generated by Django 4.2.11 on 2024-07-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0054_eybsalarydata_occupation_eybsalarydata_soc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBTInvestmentOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_title', models.CharField()),
                ('description', models.CharField()),
                ('nomination_round', models.FloatField()),
                ('launched', models.BooleanField()),
                ('opportunity_type', models.CharField()),
                ('location', models.CharField()),
                ('sub_sector', models.CharField()),
                ('levelling_up', models.BooleanField()),
                ('net_zero', models.BooleanField()),
                ('science_technology_superpower', models.BooleanField()),
                ('sector_cluster', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DBTSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_id', models.CharField()),
                ('full_sector_name', models.CharField()),
                ('sector_cluster_name', models.CharField()),
                ('sector_name', models.CharField()),
                ('sub_sector_name', models.CharField(blank=True, null=True)),
                ('sub_sub_sector_name', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorGVAValueBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_sector_name', models.CharField()),
                ('value_band_a_minimum', models.IntegerField()),
                ('value_band_b_minimum', models.IntegerField()),
                ('value_band_c_minimum', models.IntegerField()),
                ('value_band_d_minimum', models.IntegerField()),
                ('value_band_e_minimum', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sector_classification_value_band', models.CharField()),
                ('sector_classification_gva_multiplier', models.CharField()),
            ],
        ),
    ]
