# Generated by Django 4.2.14 on 2024-10-25 10:03

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0055_dbtinvestmentopportunity_dbtsector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTerritoryRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('reference_id', models.CharField(unique=True)),
                ('name', models.CharField(unique=True)),
                (
                    'type',
                    models.CharField(
                        choices=[('Country', 'Country'), ('Territory', 'Territory'), ('Region', 'Region')]
                    ),
                ),
                ('iso1_code', models.CharField(blank=True, null=True, unique=True)),
                ('iso2_code', models.CharField(blank=True, null=True, unique=True)),
                ('iso3_code', models.CharField(blank=True, null=True, unique=True)),
                ('overseas_region', models.CharField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Country, territory or region | Data Workspace',
                'verbose_name_plural': 'Countries, territories or regions | Data Workspace',
            },
        ),
    ]
