# Generated by Django 4.2.11 on 2024-07-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0055_dbtinvestmentopportunity_dbtsector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtsector',
            name='sub_sector_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dbtsector',
            name='sub_sub_sector_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
