# Generated by Django 4.2.15 on 2024-09-03 15:56

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0055_dbtinvestmentopportunity_dbtsector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_code', models.TextField()),
                ('region', models.TextField(blank=True, null=True)),
                ('european_electoral_region', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['post_code', 'region', 'european_electoral_region'],
                'indexes': [models.Index(fields=['post_code'], name='dataservice_post_co_4a1190_idx')],
            },
        ),
    ]
