# Generated by Django 4.2.16 on 2024-11-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0056_countryterritoryregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryterritoryregion',
            name='iso1_code',
            field=models.CharField(blank=True, null=True),
        ),
    ]
