# Generated by Django 4.2.15 on 2024-09-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0056_postcode'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postcode',
            index=models.Index(fields=['post_code'], name='dataservice_post_co_4a1190_idx'),
        ),
    ]
