# Generated by Django 4.2.17 on 2024-12-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0057_alter_countryterritoryregion_iso1_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBTIngestionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_name', models.CharField()),
                ('imported_file', models.CharField()),
                ('imported_when', models.DateField()),
                ('import_status', models.BooleanField(default=True)),
            ],
        ),
    ]
