# Generated by Django 4.2.17 on 2025-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0057_alter_countryterritoryregion_iso1_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comtradereport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
