# Generated by Django 4.2.16 on 2024-12-03 15:02

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0057_alter_countryterritoryregion_iso1_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, null=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, null=True, verbose_name='modified'
                    ),
                ),
                ('post_code', models.TextField()),
                ('region', models.TextField(blank=True, null=True)),
                ('european_electoral_region', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['post_code', 'region', 'european_electoral_region'],
                'indexes': [models.Index(fields=['post_code'], name='dataservice_post_co_4a1190_idx')],
            },
        ),
    ]
