# Generated by Django 4.2.17 on 2025-01-23 14:01

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0057_alter_countryterritoryregion_iso1_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='comtradereport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
