# Generated by Django 4.2.17 on 2024-12-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0058_dbtingestionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtingestionhistory',
            name='imported_when',
            field=models.DateTimeField(),
        ),
    ]
