# Generated by Django 4.2.17 on 2025-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataservices', '0058_alter_comtradereport_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comtradereport',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
