# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-23 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0031_auto_20170121_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('sender_email', models.EmailField(max_length=254, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_company_name', models.CharField(max_length=255)),
                ('sender_country', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('AEROSPACE', 'Aerospace'), ('AGRICULTURE_HORTICULTURE_AND_FISHERIES', 'Agriculture, horticulture and fisheries'), ('AIRPORTS', 'Airports'), ('AUTOMOTIVE', 'Automotive'), ('BIOTECHNOLOGY_AND_PHARMACEUTICALS', 'Biotechnology and pharmaceuticals'), ('BUSINESS_AND_CONSUMER_SERVICES', 'Business and consumer services'), ('CHEMICALS', 'Chemicals'), ('CLOTHING_FOOTWEAR_AND_FASHION', 'Clothing, footwear and fashion'), ('COMMUNICATIONS', 'Communications'), ('CONSTRUCTION', 'Construction'), ('CREATIVE_AND_MEDIA', 'Creative and media'), ('EDUCATION_AND_TRAINING', 'Education and training'), ('ELECTRONICS_AND_IT_HARDWARE', 'Electronics and IT hardware'), ('ENVIRONMENT', 'Environment'), ('FINANCIAL_AND_PROFESSIONAL_SERVICES', 'Financial and professional services'), ('FOOD_AND_DRINK', 'Food and drink'), ('GIFTWARE_JEWELLERY_AND_TABLEWARE', 'Giftware, jewellery and tableware'), ('GLOBAL_SPORTS_INFRASTRUCTURE', 'Global sports infrastructure'), ('HEALTHCARE_AND_MEDICAL', 'Healthcare and medical'), ('HOUSEHOLD_GOODS_FURNITURE_AND_FURNISHINGS', 'Household goods, furniture and furnishings'), ('LEISURE_AND_TOURISM', 'Leisure and tourism'), ('MARINE', 'Marine'), ('MECHANICAL_ELECTRICAL_AND_PROCESS_ENGINEERING', 'Mechanical electrical and process engineering'), ('METALLURGICAL_PROCESS_PLANT', 'Metallurgical process plant'), ('METALS_MINERALS_AND_MATERIALS', 'Metals, minerals and materials'), ('MINING', 'Mining'), ('OIL_AND_GAS', 'Oil and gas'), ('PORTS_AND_LOGISTICS', 'Ports and logistics'), ('POWER', 'Power'), ('RAILWAYS', 'Railways'), ('RENEWABLE_ENERGY', 'Renewable energy'), ('RETAIL_AND_LUXURY', 'Retail and luxury'), ('SECURITY', 'Security'), ('SOFTWARE_AND_COMPUTER_SERVICES', 'Software and computer services'), ('TEXTILES_INTERIOR_TEXTILES_AND_CARPETS', 'Textiles, interior textiles and carpets'), ('WATER', 'Water')], max_length=255)),
                ('is_sent', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='company.Company')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
