# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetosupplier',
            name='sender_email',
            field=models.EmailField(max_length=254),
        ),
    ]
