# Generated by Django 2.2.7 on 2019-11-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20171002_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetosupplier',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='company.Company'),
        ),
    ]
