# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_auto_20170109_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='buyer',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
    ]
