# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-01 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_auto_20170201_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='comment',
        ),
    ]
