# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-01 17:42
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_remove_buyer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='sectors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
