# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportopportunity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportopportunity',
            name='bid_timing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='bid_value',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='business_model',
            field=models.CharField(choices=[('distribution', 'Distribution'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], default='wholesale', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='company_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='full_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='open_ended_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='subsector',
            field=models.CharField(choices=[('retail', 'Retail'), ('hospitality', 'Hospitality'), ('catering', 'Catering'), ('manufacturing', 'Manufacturing')], default='retail', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='type_of_enquiry',
            field=models.CharField(choices=[('specific', 'Specific'), ('open_ended', 'Open-ended')], default='specific', max_length=10),
        ),
    ]
