# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 17:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportopportunity', '0002_auto_20170710_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportopportunity',
            name='bid_timing',
        ),
        migrations.RemoveField(
            model_name='exportopportunity',
            name='bid_value',
        ),
        migrations.RemoveField(
            model_name='exportopportunity',
            name='open_ended_description',
        ),
        migrations.RemoveField(
            model_name='exportopportunity',
            name='subsector',
        ),
        migrations.RemoveField(
            model_name='exportopportunity',
            name='type_of_enquiry',
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='additional_requirements',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='business_model_other',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='campaign',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='company_website',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='contact_preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=20), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='country',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='job_title',
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='order_deadline',
            field=models.CharField(choices=[('1-3 MONTHS', '1 to 3 months'), ('3-6 MONTHS', '3 to 6 months'), ('6-12 MONTHS', '6 months to a year'), ('NA', 'N/A')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='order_size',
            field=models.CharField(choices=[('1-1000', '1-1,000 items'), ('1000-10000', '1,000-10,000 items'), ('10000-100000', '10,001-100,000 items'), ('100000+', '100,001+ items')], default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='phone_number',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('DISCOUNT', 'Discount'), ('PREMIUM', 'Premium')], max_length=30), default=None, size=None),
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='products_other',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='target_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('catering', 'Catering'), ('manufacturing', 'Manufacturing')], max_length=30), default=None, size=None),
        ),
        migrations.AddField(
            model_name='exportopportunity',
            name='target_sectors_other',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exportopportunity',
            name='business_model',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('distribution', 'Distribution'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='exportopportunity',
            name='company_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exportopportunity',
            name='full_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exportopportunity',
            name='business_model',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('distribution', 'Distribution'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='exportopportunity',
            name='business_model',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('distribution', 'Distribution'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], max_length=30), default=None, size=None),
            preserve_default=False,
        ),
    ]
