# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-19 17:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportopportunity', '0003_auto_20170919_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportopportunity',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('DISCOUNT', 'Discount'), ('PREMIUM', 'Premium')], max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='exportopportunity',
            name='target_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('catering', 'Catering'), ('manufacturing', 'Manufacturing')], max_length=30), size=None),
        ),
    ]
