# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportopportunity', '0005_auto_20170921_1329'),
    ]
    
    operations = [
        migrations.RenameModel('ExportOpportunity', 'ExportOpportunityFood'),
    ]
