# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:07
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportopportunity', '0007_auto_20171009_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportopportunityfood',
            name='business_model',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('distribution', 'Distribution'), ('wholesale', 'Wholesale'), ('retail', 'Retail')], max_length=2000), size=None),
        ),
        migrations.AlterField(
            model_name='exportopportunityfood',
            name='business_model_other',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exportopportunityfood',
            name='products',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('DISCOUNT', 'Discount'), ('PREMIUM', 'Premium')], max_length=2000), size=None),
        ),
        migrations.AlterField(
            model_name='exportopportunityfood',
            name='target_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('retail', 'Retail'), ('hospitality', 'Hospitality'), ('catering', 'Catering'), ('manufacturing', 'Manufacturing')], max_length=2000), size=None),
        ),
        migrations.AlterField(
            model_name='exportopportunitylegal',
            name='advice_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('General-business-advice-and-partnership', 'General business advice and partnership'), ('Business-start-up-advice', 'Business start-up advice'), ('Drafting-of-contracts', 'Drafting of contracts'), ('Mergers-and-acquisitions', 'Mergers and acquisitions'), ('Immigration', 'Immigration'), ('Dispute-resolution', 'Dispute resolution')], max_length=2000), size=None),
        ),
        migrations.AlterField(
            model_name='exportopportunitylegal',
            name='advice_type_other',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exportopportunitylegal',
            name='target_sectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['', 'Other'], ('TECHNOLOGY', 'Technology'), ('FOOD_AND_DRINK', 'Food and drink'), ('RETAIL_AND_LUXURY', 'Retail'), ('FINANCIAL_AND_PROFESSIONAL_SERVICES', 'Professional services (for example, financial services or business consulting'), ('MARINE', 'Marine'), ('ENERGY', 'Energy')], max_length=2000), size=None),
        ),
    ]
