# Generated by Django 2.2.8 on 2020-02-05 17:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0102_remove_collaborationinvite_requestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExportPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_id', models.PositiveIntegerField(default=None, unique=True, verbose_name='sso user.sso_id')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('export_countries', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[])),
                ('export_commodity_codes', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[])),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_export_plans', to='company.Company')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
