# Generated by Django 2.2.8 on 2020-02-14 10:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='rules_regulations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='export_commodity_codes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='export_countries',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='sso_id',
            field=models.PositiveIntegerField(default=None, verbose_name='sso user.sso_id'),
        ),
    ]
