# Generated by Django 2.2.10 on 2020-03-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0004_exportplanactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyobjectives',
            name='companyexportplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_objectives', to='exportplan.CompanyExportPlan'),
        ),
        migrations.AlterField(
            model_name='exportplanactions',
            name='companyexportplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_plan_actions', to='exportplan.CompanyExportPlan'),
        ),
    ]
