# Generated by Django 2.2.10 on 2020-03-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0005_auto_20200323_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyexportplan',
            old_name='target_countries',
            new_name='target_markets',
        ),
    ]
