# Generated by Django 2.2.10 on 2020-05-12 10:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0006_auto_20200327_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='brand_product_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
