# Generated by Django 2.2.10 on 2020-06-04 10:08

import directory_validators.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0007_companyexportplan_brand_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyobjectives',
            name='planned_reviews',
            field=models.TextField(blank=True, default='', null=True, validators=[directory_validators.string.no_html]),
        ),
        migrations.AlterField(
            model_name='companyobjectives',
            name='owner',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
