# Generated by Django 2.2.10 on 2020-06-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0008_auto_20200604_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyexportplan',
            name='planned_review',
        ),
    ]
