# Generated by Django 2.2.13 on 2020-07-14 07:34

import directory_validators.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0009_remove_companyexportplan_planned_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='business_performance',
            field=models.TextField(blank=True, default='', null=True, validators=[directory_validators.string.no_html]),
        ),
    ]
