# Generated by Django 2.2.13 on 2020-07-14 15:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0010_auto_20200714_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyexportplan',
            name='research_competition',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='research_consumer_demand',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='research_product_trends',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='research_unique_selling',
        ),
        migrations.AddField(
            model_name='companyexportplan',
            name='target_markets_research',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
