# Generated by Django 2.2.13 on 2020-08-04 12:25

import directory_validators.string
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0012_auto_20200804_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteToMarkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('route', models.TextField(default='', null=True, validators=[directory_validators.string.no_html])),
                ('promote', models.TextField(blank=True, default='', validators=[directory_validators.string.no_html])),
                ('market_promotional_channel', models.TextField(blank=True, default='', validators=[directory_validators.string.no_html])),
                ('companyexportplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_to_markets', to='exportplan.CompanyExportPlan')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
