# Generated by Django 2.2.13 on 2020-08-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0013_routetomarkets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyexportplan',
            old_name='brand_product_details',
            new_name='about_your_business',
        ),
    ]
