# Generated by Django 2.2.13 on 2020-08-14 07:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0015_auto_20200807_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='adaptation_target_market',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
