# Generated by Django 2.2.13 on 2020-09-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0018_auto_20200818_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyexportplan',
            old_name='rational',
            new_name='rationale',
        ),
    ]
