# Generated by Django 2.2.13 on 2020-10-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0020_auto_20201007_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetomarkets',
            name='promote',
            field=models.CharField(blank=True, choices=[('MARKETING_AT_EVENTS', 'Marketing at events'), ('ONLINE_MARKETING', 'Online marketing'), ('OTHER', 'Other')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='routetomarkets',
            name='route',
            field=models.CharField(blank=True, choices=[('DIRECT_SALES', 'Direct sales'), ('INTERNATIONAL_E_COMMERCE', 'International e-commerce'), ('AGENT_OR_DISTRIBUTOR', 'Agent or distributor'), ('LICENSING', 'Licensing'), ('FRANCHISING', 'Franchising'), ('JOINT_VENTURES', 'Joint ventures'), ('SET_UP_A_BUSINESS_ABROAD', 'Set up a business abroad'), ('OTHER', 'Other')], default='', max_length=30, null=True),
        ),
    ]
