# Generated by Django 2.2.13 on 2020-11-16 16:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0021_auto_20201019_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyexportplan',
            name='rules_regulations',
        ),
        migrations.AddField(
            model_name='companyexportplan',
            name='ui_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
    ]
