# Generated by Django 2.2.13 on 2020-11-17 15:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0022_auto_20201116_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexportplan',
            name='ui_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
