# Generated by Django 2.2.13 on 2021-01-25 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0024_auto_20210121_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyobjectives',
            options={'verbose_name_plural': 'Company Objectives'},
        ),
        migrations.AlterModelOptions(
            name='exportplanactions',
            options={'verbose_name_plural': 'Export Plan Actions'},
        ),
        migrations.AlterModelOptions(
            name='fundingcreditoptions',
            options={'verbose_name_plural': 'Funding Credit Options'},
        ),
        migrations.AlterModelOptions(
            name='routetomarkets',
            options={'verbose_name_plural': 'Route To Markets'},
        ),
        migrations.AlterModelOptions(
            name='targetmarketdocuments',
            options={'verbose_name_plural': 'Target Market Documents'},
        ),
    ]
