# Generated by Django 2.2.13 on 2021-01-26 17:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0026_companyexportplan_ui_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='getting_paid',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
