# Generated by Django 2.2.13 on 2021-02-18 13:59

import directory_validators.string
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0029_auto_20210211_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingcreditoptions',
            name='funding_option',
            field=models.CharField(blank=True, choices=[('BANK_LOAN', 'Bank loan'), ('GOVERNMENT', 'Finance support from government'), ('FINANCE_PLATFORMS', 'Finance platforms'), ('PEER_TO_PEER_LOANS', 'Peer-to-peer loan'), ('EQUITY_FINANCE', 'Equity finance'), ('OTHER', 'Other')], default='', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='BusinessRisks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('risk', models.TextField(blank=True, default='', validators=[directory_validators.string.no_html])),
                ('contingency_plan', models.TextField(blank=True, default='', validators=[directory_validators.string.no_html])),
                ('risk_likelihood', models.CharField(blank=True, choices=[('RARE', 'Rare'), ('UNLIKELY', 'Unlikely'), ('POSSIBLE', 'Possible'), ('LIKELY', 'Likely'), ('CERTAIN', 'Certain')], default='', max_length=30, null=True)),
                ('risk_impact', models.CharField(blank=True, choices=[('TRIVIAL', 'Trivial'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major'), ('SEVERE', 'Severe')], default='', max_length=30, null=True)),
                ('companyexportplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_risks', to='exportplan.CompanyExportPlan')),
            ],
            options={
                'verbose_name_plural': 'Business Risks',
            },
        ),
    ]
