# Generated by Django 2.2.13 on 2021-03-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0030_auto_20210218_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyexportplan',
            name='compliance',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='consumer_demand',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='export_certificates',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='promotion_channels',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='resource_needed',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='spend_marketing',
        ),
    ]
