# Generated by Django 2.2.22 on 2021-06-14 13:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0035_auto_20210609_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='sectors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='companyexportplan',
            name='target_markets',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
