# Generated by Django 2.2.22 on 2021-06-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0037_exportplanactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyexportplan',
            name='sectors',
        ),
        migrations.RemoveField(
            model_name='companyexportplan',
            name='target_markets',
        ),
        migrations.DeleteModel(
            name='ExportPlanActions',
        ),
    ]
