# Generated by Django 2.2.24 on 2021-07-21 14:34

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0006_businessuser_usermarket_userproduct'),
        ('exportplan', '0038_auto_20210614_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='business_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalisation.BusinessUser'),
        ),
    ]
