# Generated by Django 2.2.24 on 2021-07-21 14:34

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0006_businessuser_usermarket_userproduct'),
        ('exportplan', '0038_auto_20210614_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='business_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personalisation.BusinessUser'),
        ),
        migrations.CreateModel(
            name='ExportPlanProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('companyexportplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_plan_product', to='exportplan.CompanyExportPlan')),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalisation.UserProduct')),
            ],
            options={
                'unique_together': {('companyexportplan', 'user_product')},
            },
        ),
        migrations.CreateModel(
            name='ExportPlanMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('companyexportplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_plan_market', to='exportplan.CompanyExportPlan')),
                ('user_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personalisation.UserMarket')),
            ],
            options={
                'unique_together': {('companyexportplan', 'user_market')},
            },
        ),
    ]
