# Generated by Django 2.2.24 on 2021-07-26 14:50

import django.core.validators
from django.db import migrations, models


def split_dates(apps, schema_editor):
    CompanyObjective = apps.get_model('exportplan', 'CompanyObjectives')
    for objective in CompanyObjective.objects.all():
        if objective.start_date:
            objective.start_month = objective.start_date.month
            objective.start_year = objective.start_date.year
        if objective.end_date:
            objective.end_month = objective.end_date.month
            objective.end_year = objective.end_date.year
        objective.save()


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0038_auto_20210614_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyobjectives',
            name='end_month',
            field=models.IntegerField(blank=True, null=True, validators=[
                                      django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='companyobjectives',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, validators=[
                                      django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AddField(
            model_name='companyobjectives',
            name='start_month',
            field=models.IntegerField(blank=True, null=True, validators=[
                                      django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='companyobjectives',
            name='start_year',
            field=models.IntegerField(blank=True, null=True, validators=[
                                      django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.RunPython(split_dates),
    ]
