# Generated by Django 2.2.24 on 2021-07-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0039_auto_20210721_1434'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exportplanproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exportplanproduct',
            name='companyexportplan',
        ),
        migrations.RemoveField(
            model_name='exportplanproduct',
            name='user_product',
        ),
        migrations.DeleteModel(
            name='ExportPlanMarket',
        ),
        migrations.DeleteModel(
            name='ExportPlanProduct',
        ),
    ]
