# Generated by Django 2.2.24 on 2021-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0039_auto_20210726_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyexportplan',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
