# Generated by Django 2.2.24 on 2021-07-23 09:59

from django.db import migrations, models
import django.db.models.deletion
from personalisation.models import BusinessUser, UserMarket, UserProduct
from exportplan.models import ExportPlanMarket, ExportPlanProduct


def create_multiple_products_markets(apps, schema_editor):
    Exportplan = apps.get_model('exportplan', 'CompanyExportPlan')
    ExportPlanMarket = apps.get_model('exportplan', 'ExportPlanMarket')
    ExportPlanProduct = apps.get_model('exportplan', 'ExportPlanProduct')
    BusinessUser = apps.get_model('personalisation', 'BusinessUser')
    UserMarket = apps.get_model('personalisation', 'UserMarket')
    UserProduct = apps.get_model('personalisation', 'UserProduct')

    for exportplan in Exportplan.objects.all():
        business_user = BusinessUser.objects.get_or_create(sso_id=exportplan.sso_id)
        if len(exportplan.export_countries):
            user_market = UserMarket.objects.get_or_create(
                business_user=business_user[0],
                data=exportplan.export_countries[0],
                country_iso2_code=exportplan.export_countries[0]['country_iso2_code']
            )
            ExportPlanMarket.objects.create(
                companyexportplan=exportplan,
                user_market=user_market[0]
            )

        if len(exportplan.export_commodity_codes):
            user_product = UserProduct.objects.get_or_create(
                business_user=business_user[0],
                product_data=exportplan.export_commodity_codes[0],
            )
            ExportPlanProduct.objects.create(
                companyexportplan=exportplan,
                user_product=user_product[0]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('exportplan', '0039_auto_20210721_1434'),
    ]

    operations = [
        migrations.RunPython(
            create_multiple_products_markets, migrations.RunPython.noop
        ),
    ]