# Generated by Django 4.1.9 on 2023-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exportplan', '0042_populate_exportplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexportplan',
            name='about_your_business',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='adaptation_target_market',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='direct_costs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='export_commodity_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='export_countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='funding_and_credit',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='getting_paid',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='marketing_approach',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='objectives',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='overhead_costs',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='target_markets_research',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='total_cost_and_price',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='travel_business_policies',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='ui_options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='companyexportplan',
            name='ui_progress',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
