# Generated by Django 4.1.13 on 2024-01-15 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('exportplan', '0043_alter_companyexportplan_about_your_business_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyexportplan',
            options={'ordering': ['-modified'], 'verbose_name': 'Export Plan', 'verbose_name_plural': 'Export Plans'},
        ),
    ]
