# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('sector', models.CharField(max_length=255)),
                ('exported_before', models.BooleanField()),
                ('regular_exporter', models.BooleanField()),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sole_trader', models.BooleanField()),
                ('sso_id', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
