# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportreadiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageresult',
            name='used_online_marketplace',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
