# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportreadiness', '0002_triageresult_used_online_marketplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageresult',
            name='used_online_marketplace',
            field=models.NullBooleanField(),
        ),
    ]
