# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportreadiness', '0003_auto_20171019_1317'),
        ('exportreadiness', '0003_auto_20171019_1453'),
    ]

    operations = [
    ]
