# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportreadiness', '0008_auto_20171024_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageresult',
            name='sole_trader',
            field=models.NullBooleanField(),
        ),
    ]
