# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportreadiness', '0013_auto_20171205_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleread',
            name='sso_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
