# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-09 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportreadiness', '0013_auto_20171129_1601'),
        ('exportreadiness', '0015_auto_20171211_1035'),
    ]

    operations = [
    ]
