# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-13 11:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=8, validators=[django.core.validators.MinValueValidator(8)])),
                ('website', models.URLField(max_length=255)),
                ('description', models.TextField()),
                ('aims', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
