# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20161024_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
    ]
