# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 11:09
from __future__ import unicode_literals
import json

from django.db import migrations


def clear_sectors(apps, schema_editor):
    CompanyModel = apps.get_model("company", "Company")
    for company in CompanyModel.objects.all():
        company.sectors = json.dumps([])
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20161029_2200'),
    ]

    operations = [
        migrations.RunPython(clear_sectors)
    ]
