# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 11:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20161030_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sectors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
