# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20161030_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
