# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-30 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20161030_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.CharField(blank=True, choices=[('', 'Please select'), ('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1,000'), ('1001-10000', '1,001-10,000'), ('10001+', '10,001+')], default='', max_length=20, null=True),
        ),
    ]
