# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 14:34
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20161030_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=core.helpers.PathAndRename('/company_logos')),
        ),
    ]
