# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-31 15:04
from __future__ import unicode_literals

import company.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20161031_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=company.helpers.PathAndRename(sub_path='/company_logos')),
        ),
    ]
