# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-18 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20161110_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True, default=None),
            preserve_default=False,
        ),
    ]
