# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_company_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.CharField(blank=True, choices=[('', 'Please select an option'), ('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1,000'), ('1001-10000', '1,001-10,000'), ('10001+', '10,001+')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='export_status',
            field=models.CharField(choices=[('', 'Please select an option'), ('YES', 'Yes, in the last year'), ('ONE_TWO_YEARS_AGO', 'Yes, 1 to 2 years ago'), ('OVER_TWO_YEARS_AGO', 'Yes, but more than 2 years ago'), ('NOT_YET', 'No, but we are preparing to'), ('NO_INTENTION', 'No, we are not planning to sell overseas')], max_length=20, validators=[]),
        ),
    ]
