# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_auto_20161124_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercasestudy',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_case_studies', to='company.Company'),
            preserve_default=False,
        ),
    ]
