# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_suppliercasestudy_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierCaseStudy',
            new_name='CompanyCaseStudy',
        ),
    ]
