# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20161124_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
