# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-24 14:00
from __future__ import unicode_literals

import company.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20161124_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_one',
            field=models.FileField(blank=True, default='', null=True, upload_to=company.helpers.PathAndRename(sub_path='/supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_three',
            field=models.FileField(blank=True, default='', null=True, upload_to=company.helpers.PathAndRename(sub_path='/supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_two',
            field=models.FileField(blank=True, default='', null=True, upload_to=company.helpers.PathAndRename(sub_path='/supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='video_one',
            field=models.FileField(blank=True, default='', null=True, upload_to=company.helpers.PathAndRename(sub_path='/supplier_case_study')),
        ),
    ]
