
# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-30 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_company_letter_verification_code'),
        ('company', '0015_auto_20161129_1621'),
    ]

    operations = [
    ]
