# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-05 15:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20161201_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='letter_verification_code',
        ),
        migrations.AddField(
            model_name='company',
            name='contact_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='verification code'),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_with_code',
            field=models.BooleanField(default=False),
        ),
    ]
