# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-08 10:56
from __future__ import unicode_literals

import company.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_auto_20161206_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verification_letter_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='verification_code',
            field=models.CharField(blank=True, default=company.helpers.generate_verification_code, max_length=255, null=True, verbose_name='verification code'),
        ),
    ]
