# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-20 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20161219_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter_url',
            field=models.URLField(blank=True, default='', max_length=255, null=True),
        ),
    ]
