# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-12-21 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_auto_20161220_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycasestudy',
            name='image_one_caption',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companycasestudy',
            name='image_three_caption',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companycasestudy',
            name='image_two_caption',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='companycasestudy',
            name='short_summary',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
