# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-05 12:15
from __future__ import unicode_literals

import core.helpers
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_auto_20161221_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='revenue',
        ),
        migrations.AddField(
            model_name='company',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_of_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.CharField(blank=True, choices=[('', 'Please select an option'), ('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1,000'), ('1001-10000', '1,001-10,000'), ('10001+', '10,001+')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, default='', upload_to=core.helpers.PathAndRename(sub_path='/company_logos')),
        ),
        migrations.AlterField(
            model_name='company',
            name='sectors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='verification_code',
            field=models.CharField(blank=True, default=core.helpers.generate_verification_code, max_length=255, verbose_name='verification code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_one',
            field=models.FileField(blank=True, default='', upload_to=core.helpers.PathAndRename(sub_path='/supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_three',
            field=models.FileField(blank=True, default='', upload_to=core.helpers.PathAndRename(sub_path='/supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_two',
            field=models.FileField(blank=True, default='', upload_to=core.helpers.PathAndRename(sub_path='/supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_three_caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_two',
            field=models.FileField(blank=True, default='', upload_to=core.helpers.PathAndRename(sub_path='/supplier_case_study')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_two_caption',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='short_summary',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='testimonial',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='testimonial_company',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='testimonial_job_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='testimonial_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='video_one',
            field=models.FileField(blank=True, default='', upload_to=core.helpers.PathAndRename(sub_path='/supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
