# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-03 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_remove_bad_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companycasestudy',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Companies are automatically published based on profile completeness - they must have description or summary, be verified, and have an email address.'),
        ),
    ]
