# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-03 11:42
from __future__ import unicode_literals

from django.db import migrations, transaction
from django.template.defaultfilters import slugify


@transaction.atomic
def add_company_slugs(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    for company in Company.objects.all():
        company.slug = slugify(company.name)[:50]
        company.save()


def add_case_study_slugs(apps, schema_editor):
    CompanyCaseStudy = apps.get_model('company', 'CompanyCaseStudy')
    for case_study in CompanyCaseStudy.objects.all():
        case_study.slug = slugify(case_study.title)[:50]
        case_study.save()


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_auto_20170203_1137'),
    ]

    operations = [
        migrations.RunPython(add_company_slugs, noop),
        migrations.RunPython(add_case_study_slugs, noop),
    ]
