# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 15:24
from __future__ import unicode_literals

import company.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_add_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to=company.helpers.PathAndRename(sub_path='company_logos')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_one',
            field=models.ImageField(blank=True, default='', upload_to=company.helpers.PathAndRename(sub_path='supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_three',
            field=models.ImageField(blank=True, default='', upload_to=company.helpers.PathAndRename(sub_path='supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_two',
            field=models.ImageField(blank=True, default='', upload_to=company.helpers.PathAndRename(sub_path='supplier_case_study')),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='video_one',
            field=models.FileField(blank=True, default='', upload_to=company.helpers.PathAndRename(sub_path='supplier_case_study')),
        ),
    ]
