# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-27 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_auto_20170224_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='verification_date',
            field=models.DateTimeField(null=True),
        ),
    ]
