# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-06 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_company_verification_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='verification_date',
            new_name='date_verification_letter_sent',
        ),
    ]
