# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-03 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_remove_company_contact_details'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
