# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-05 11:48
from __future__ import unicode_literals

from django.core import management
from django.db import migrations

def add_company_search_index_and_populate(apps, schema_editor):
    management.call_command('rebuild_elasticsearch_index')


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_add_search_index'),
    ]

    operations = [
        # calling rebuild elasticserach index uses the Company model. Once new
        # fields are added to the Company model, but the schema has not yet
        # been migrated then the "rebuild elasticserach index" will fail
        migrations.RunPython(noop, noop)
    ]
