# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-05 11:48
from __future__ import unicode_literals

from django.db import migrations

from company import utils


def add_company_search_index_and_populate(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    utils.populate_elasticsearch(Company)


def noop(*args, **kwargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_add_search_index'),
    ]

    operations = [
        migrations.RunPython(add_company_search_index_and_populate, noop)
    ]
