# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-05 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_auto_20170505_1148'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
