# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-20 14:26
from __future__ import unicode_literals

import re

from django.db import migrations


def forwards(apps, schema_editor):
    regex_pattern = r'[!\"#$%&\'()*+-./:;<=>?@[\\]^_{|}~\t\n]'
    Company = apps.get_model('company', 'Company')
    for company in Company.objects.filter(keywords__iregex=regex_pattern):
        company.keywords = re.sub(regex_pattern, ',', company.keywords)
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_rebuild_elasticserach_index'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
