# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-23 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0045_auto_20170620_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='verified_with_trade_association',
            field=models.BooleanField(default=False),
        ),
    ]
