# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-26 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_company_verified_with_trade_association'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='verified_with_trade_association',
            new_name='verified_with_preverified_enrolment',
        ),
    ]
