# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-18 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_auto_20170630_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_exported_before',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
