# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-19 10:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_auto_20170718_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='export_destinations_other',
            field=models.CharField(blank=True, default='', help_text='Of the countries the project have not prioritised,which does the company want to export to (free text).', max_length=1000),
        ),
        migrations.AddField(
            model_name='company',
            name='export_destinations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], help_text='Of the countries the project have prioritised,which does the company want to export to (whitelisted)'),
        ),
    ]
