# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-30 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0052_auto_20170719_1054'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
