# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-30 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0053_auto_20170727_0919'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
