# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-09 10:06
from __future__ import unicode_literals

import directory_validators.company
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0054_auto_20170731_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='', validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='email_full_name',
            field=models.CharField(blank=True, default='', max_length=200, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='export_destinations_other',
            field=models.CharField(blank=True, default='', help_text='Of the countries the project have not prioritised,which does the company want to export to (free text).', max_length=1000, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='keywords',
            field=models.TextField(blank=True, default='', validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_company_number', message='Company number must be 8 characters', regex='^[A-Za-z0-9]{8}$'), directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='po_box',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_full_name',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=250, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='description',
            field=models.CharField(max_length=1000, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_one_caption',
            field=models.CharField(blank=True, default='', max_length=200, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_three_caption',
            field=models.CharField(blank=True, default='', max_length=200, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='image_two_caption',
            field=models.CharField(blank=True, default='', max_length=200, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='keywords',
            field=models.TextField(validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='short_summary',
            field=models.CharField(blank=True, default='', max_length=200, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='testimonial',
            field=models.CharField(blank=True, default='', max_length=1000, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='testimonial_company',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='testimonial_job_title',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='testimonial_name',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='title',
            field=models.CharField(max_length=100, validators=[directory_validators.company.no_html]),
        ),
    ]
