# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_unsubscribed'),
        ('company', '0058_auto_20170816_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('new_owner_email', models.EmailField(max_length=254, unique=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.Company')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.User')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
