# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0060_collaboratorinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipinvite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
