# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-06 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0061_ownershipinvite_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorinvite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
