# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-08-17 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0062_collaboratorinvite_uuid'),
    ]

    # This migration was rebuilding the ES index, but the DocType of Company
    # changed, so it was moved to 0066
    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)
    ]
