# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0064_auto_20171002_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='campaign_tag',
            field=models.CharField(blank=True, choices=[('food-is-great', 'food-is-great'), ('legal-is-great', 'legal-is-great')], help_text='Marks the company for use on the specified campaign page', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companycasestudy',
            name='campaign_tag',
            field=models.CharField(blank=True, choices=[('food-is-great', 'food-is-great'), ('legal-is-great', 'legal-is-great')], help_text='Marks the casestudy for use on the specified campaign page', max_length=100, null=True),
        ),
    ]
