# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0065_auto_20171003_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date_published',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='date_verification_letter_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
