# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0066_auto_20171004_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='campaign_tag',
            field=models.CharField(blank=True, choices=[(('food-is-great', 'food-is-great'), ('food-is-great', 'food-is-great')), (('legal-is-great', 'legal-is-great'), ('legal-is-great', 'legal-is-great'))], help_text='Marks the company for use on the specified campaign page', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='campaign_tag',
            field=models.CharField(blank=True, choices=[(('food-is-great', 'food-is-great'), ('food-is-great', 'food-is-great')), (('legal-is-great', 'legal-is-great'), ('legal-is-great', 'legal-is-great'))], help_text='Marks the casestudy for use on the specified campaign page', max_length=100, null=True),
        ),
    ]
