# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20180103_1159'),
        ('company', '0068_auto_20171011_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorinvite',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
        migrations.AlterField(
            model_name='ownershipinvite',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
    ]
