# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0069_auto_20180103_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_exporting_goods',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_exporting_services',
            field=models.BooleanField(default=False),
        ),
    ]
