# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0070_auto_20180305_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='campaign_tag',
            field=models.CharField(blank=True, choices=[('food-is-great', 'food-is-great'), ('legal-is-great', 'legal-is-great'), ('industry-list-page', 'industry-list-page')], help_text='Marks the company for use on the specified page', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companycasestudy',
            name='campaign_tag',
            field=models.CharField(blank=True, choices=[('food-is-great', 'food-is-great'), ('legal-is-great', 'legal-is-great'), ('industry-list-page', 'industry-list-page')], help_text='Marks the casestudy for use on the specified campaign page', max_length=100, null=True),
        ),
    ]
