# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0071_auto_20180416_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_showcase_company',
            field=models.BooleanField(default=False),
        ),
    ]
