# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0072_company_is_showcase_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='verified_with_govuk_verify',
            field=models.BooleanField(default=False),
        ),
    ]
