# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0072_company_is_showcase_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='has_exported_before',
            field=models.NullBooleanField(),
        ),
    ]
