# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0074_auto_20181121_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='campaign_tag',
        ),
        migrations.RemoveField(
            model_name='companycasestudy',
            name='campaign_tag',
        ),
    ]
