# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0075_auto_20190211_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('collaborator_email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='collaboratorrequest',
            unique_together=set([('collaborator_email', 'company')]),
        ),
    ]
