# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-19 10:14
from __future__ import unicode_literals

from django.db import migrations



def forwards(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    Company.objects.all().update(company_type='COMPANIES_HOUSE')


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0077_auto_20190218_1017'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
