# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0078_auto_20190219_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_uk_isd_company',
            field=models.BooleanField(default=False),
        ),
    ]
