# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0079_company_is_uk_isd_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='is_published',
            new_name='is_published_investment_support_directory',
        ),
        migrations.AddField(
            model_name='company',
            name='is_published_find_a_supplier',
            field=models.BooleanField(default=False, help_text='Companies that have a published profile on FAS completeness - they must have description or summary, be verified, and have an email address.'),
        ),
    ]
