# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 19:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0080_auto_20190312_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='expertise_countries',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], help_text='The countries that this company has expertise in,this allows searching and filtering for this selection'),
        ),
        migrations.AddField(
            model_name='company',
            name='expertise_industries',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], help_text='The industries that this company has expertise in,this allows searching and filtering for this selection'),
        ),
        migrations.AddField(
            model_name='company',
            name='expertise_languages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], help_text='The languages that this company has expertise in,this allows searching and filtering for this selection'),
        ),
        migrations.AddField(
            model_name='company',
            name='expertise_regions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], help_text='The regions that this company has expertise in,this allows searching and filtering for this selection'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_published_find_a_supplier',
            field=models.BooleanField(default=False, help_text='Companies that have a published profile on FAS completeness - they must have description or summary, be verified, and have an email address.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_published_investment_support_directory',
            field=models.BooleanField(default=False, help_text='Companies that have a published profile on investment support.completeness - they must have description or summary, be verified, and have an email address.'),
        ),
    ]
