# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 08:49
from __future__ import unicode_literals

from django.db import migrations


def tokenize_keywords(keywords):
    if not keywords:
        return []
    sanitized = keywords.replace(', ', ',').replace(' ,', ',').strip(' ,')
    return sanitized.split(',')


def forwards(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    for company in Company.objects.all():
        expertise = company.expertise_products_services or {}
        expertise.setdefault('other', [])
        if company.keywords:
            expertise['other'] += tokenize_keywords(company.keywords)
        company.expertise_products_services = expertise
        company.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0083_auto_20190409_1640'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
