# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0084_auto_20190508_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('COMPANIES_HOUSE', 'A business registered with Companies House'), ('CHARITY', 'Charity'), ('PARTNERSHIP', 'Partnership'), ('SOLE_TRADER', 'Sole Trader'), ('OTHER', 'Other UK business not registered in Companies House')], default='COMPANIES_HOUSE', max_length=15),
        ),
    ]
