# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-22 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0085_auto_20190708_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_registration_letter_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_registration_letter_sent',
            field=models.BooleanField(default=False),
        ),
    ]
