# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-28 09:29
from __future__ import unicode_literals

import directory_validators.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0086_auto_20190722_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companies_house_company_status',
            field=models.CharField(blank=True, default='', max_length=255, validators=[directory_validators.string.no_html]),
        ),
    ]
