# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-15 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0087_company_companies_house_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_identity_check_message_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_identity_check_message_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_with_identity_check',
            field=models.BooleanField(default=False),
        ),
    ]
