# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0093_companyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationinvite',
            name='company_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyUser', null=True, blank=True),
            preserve_default=False,
        ),
    ]
