# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 12:18
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    CompanyUser = apps.get_model('company', 'CompanyUser')
    Supplier = apps.get_model('supplier', 'Supplier')
    SupplierEmailNotification = apps.get_model('notifications', 'SupplierEmailNotification')
    CollaborationInvite = apps.get_model('company', 'CollaborationInvite')

    for supplier in Supplier.objects.all():
        CompanyUser.objects.create(
            sso_id=supplier.sso_id,
            name=supplier.name,
            company=supplier.company,
            company_email=supplier.company_email,
            is_active=supplier.is_active,
            date_joined=supplier.date_joined,
            mobile_number=supplier.mobile_number,
            unsubscribed=supplier.unsubscribed,
            role=supplier.role,
            created=supplier.created,
            modified=supplier.modified,
        )

    for notifiction in SupplierEmailNotification.objects.all():
    	notifiction.company_user = CompanyUser.objects.get(sso_id=notifiction.supplier.sso_id)
    	notifiction.save()

    for invite in CollaborationInvite.objects.all():
        invite.company_user = CompanyUser.objects.get(sso_id=invite.supplier.sso_id)
        invite.save()


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_auto_20190918_1043'),
        ('company', '0094_collaborationinvite_company_user'),
        ('notifications', '0009_supplieremailnotification_company_user'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop)
    ]
