# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0095_auto_20191108_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratorinvite',
            name='company',
        ),
        migrations.RemoveField(
            model_name='collaboratorinvite',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='ownershipinvite',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ownershipinvite',
            name='requestor',
        ),
        migrations.DeleteModel(
            name='CollaboratorInvite',
        ),
        migrations.DeleteModel(
            name='OwnershipInvite',
        ),
    ]
