# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 15:07
from __future__ import unicode_literals

import core.helpers
import directory_validators.company
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0096_auto_20191108_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='expertise_countries',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='company',
            name='expertise_industries',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='company',
            name='expertise_languages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='company',
            name='expertise_products_services',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='company',
            name='expertise_regions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='company',
            name='export_destinations',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='company',
            name='export_destinations_other',
            field=models.CharField(blank=True, default='', max_length=1000, validators=[directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_published_investment_support_directory',
            field=models.BooleanField(default=False, help_text='Companies that have a published profile on investment support completeness - they must have description or summary, be verified, and have an email address.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='number',
            field=models.CharField(blank=True, help_text='For companies registered in companies house this is their companies house number. For non-companies house companies this is a randomly string.', max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_company_number', message='Company number must be 8 characters', regex='^[A-Za-z0-9]{8}$'), directory_validators.company.no_html]),
        ),
        migrations.AlterField(
            model_name='company',
            name='verification_code',
            field=models.CharField(blank=True, default=core.helpers.generate_verification_code, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
