# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0097_auto_20191108_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationinvite',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
        migrations.AlterField(
            model_name='collaborationinvite',
            name='company_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyUser'),
            preserve_default=False,
        ),
    ]
