# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0098_auto_20191108_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborationinvite',
            name='requestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
    ]
