# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-19 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0099_auto_20191108_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('MEMBER', 'Member')], max_length=15)),
                ('requestor_name', models.CharField(blank=True, max_length=100)),
                ('requestor_role', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('MEMBER', 'Member')], max_length=15)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyUser')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
