# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-22 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0100_collaborationrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collaboratorrequest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='collaboratorrequest',
            name='company',
        ),
        migrations.DeleteModel(
            name='CollaboratorRequest',
        ),
    ]
