# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-19 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0100_collaborationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaborationrequest',
            old_name='requestor_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='requestor_role',
        ),
    ]
