# Generated by Django 2.2.8 on 2019-12-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0101_collaborationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationinvite',
            name='requestor',
        ),
    ]
