# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-19 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0101_auto_20191119_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationrequest',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
        ),
    ]
