# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-19 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0102_collaborationrequest_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborationrequest',
            name='company',
        ),
    ]
