# Generated by Django 2.2.13 on 2020-06-25 20:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0103_auto_20200212_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hs_codes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='HsCodeSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=10)),
                ('sector', models.CharField(choices=[('AEROSPACE', 'Aerospace'), ('ADVANCED_MANUFACTURING', 'Advanced manufacturing'), ('AIRPORTS', 'Airports'), ('AGRICULTURE_HORTICULTURE_AND_FISHERIES', 'Agriculture, horticulture and fisheries'), ('AUTOMOTIVE', 'Automotive'), ('BIOTECHNOLOGY_AND_PHARMACEUTICALS', 'Biotechnology and pharmaceuticals'), ('BUSINESS_AND_CONSUMER_SERVICES', 'Business and consumer services'), ('CHEMICALS', 'Chemicals'), ('CLOTHING_FOOTWEAR_AND_FASHION', 'Clothing, footwear and fashion'), ('COMMUNICATIONS', 'Communications'), ('CONSTRUCTION', 'Construction'), ('CREATIVE_AND_MEDIA', 'Creative and media'), ('EDUCATION_AND_TRAINING', 'Education and training'), ('ELECTRONICS_AND_IT_HARDWARE', 'Electronics and IT hardware'), ('ENVIRONMENT', 'Environment'), ('FINANCIAL_AND_PROFESSIONAL_SERVICES', 'Financial and professional services'), ('FOOD_AND_DRINK', 'Food and drink'), ('GIFTWARE_JEWELLERY_AND_TABLEWARE', 'Giftware, jewellery and tableware'), ('GLOBAL_SPORTS_INFRASTRUCTURE', 'Global sports infrastructure'), ('HEALTHCARE_AND_MEDICAL', 'Healthcare and medical'), ('HOUSEHOLD_GOODS_FURNITURE_AND_FURNISHINGS', 'Household goods, furniture and furnishings'), ('LIFE_SCIENCES', 'Life sciences'), ('LEISURE_AND_TOURISM', 'Leisure and tourism'), ('LEGAL_SERVICES', 'Legal services'), ('MARINE', 'Marine'), ('MECHANICAL_ELECTRICAL_AND_PROCESS_ENGINEERING', 'Mechanical electrical and process engineering'), ('METALLURGICAL_PROCESS_PLANT', 'Metallurgical process plant'), ('METALS_MINERALS_AND_MATERIALS', 'Metals, minerals and materials'), ('MINING', 'Mining'), ('OIL_AND_GAS', 'Oil and gas'), ('PORTS_AND_LOGISTICS', 'Ports and logistics'), ('POWER', 'Power'), ('RAILWAYS', 'Railways'), ('RENEWABLE_ENERGY', 'Renewable energy'), ('RETAIL_AND_LUXURY', 'Retail and luxury'), ('SECURITY', 'Security'), ('SOFTWARE_AND_COMPUTER_SERVICES', 'Software and computer services'), ('TEXTILES_INTERIOR_TEXTILES_AND_CARPETS', 'Textiles, interior textiles and carpets'), ('WATER', 'Water')], max_length=100)),
            ],
            options={
                'unique_together': {('hs_code', 'sector')},
            },
        ),
    ]
