# Generated by Django 2.2.13 on 2020-07-06 10:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0103_auto_20200212_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hs_codes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='HsCodeSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=10)),
                ('product', models.TextField()),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('hs_code', 'sector')},
            },
        ),
    ]
