# Generated by Django 2.2.24 on 2021-07-02 15:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0104_auto_20200706_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companies_house_sic_codes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
