# Generated by Django 4.1.9 on 2023-07-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('company', '0106_alter_company_companies_house_sic_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycasestudy',
            name='is_published_case_study',
            field=models.BooleanField(
                default=True, help_text='Case studies that are published will be visible to all users'
            ),
        ),
    ]
