# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0068_auto_20171011_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('sso_id', models.PositiveIntegerField(unique=True, verbose_name='sso user.sso_id')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name')),
                ('company_email', models.EmailField(max_length=254, unique=True, verbose_name='company email')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('unsubscribed', models.BooleanField(default=False, help_text='Designates whether this user should receive notifications', verbose_name='unsubscribed')),
                ('is_company_owner', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='company.Company')),
            ],
            options={
                'ordering': ('-created', '-modified'),
            },
        ),
    ]
