# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 11:59
from __future__ import unicode_literals

from django.db import migrations


def create_suppliers(apps, schema_editor):
    Supplier = apps.get_model("supplier", "Supplier")
    User = apps.get_model("user", "User")
    for user in User.objects.all():
        Supplier.objects.create(
            id=user.id,
            sso_id=user.sso_id,
            name=user.name,
            company=user.company,
            company_email=user.company_email,
            is_active=user.is_active,
            date_joined=user.date_joined,
            mobile_number=user.mobile_number,
            unsubscribed=user.unsubscribed,
            is_company_owner=user.is_company_owner,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20170907_1552'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_suppliers, migrations.RunPython.noop),
    ]
