# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20180109_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='govuk_verify_address',
            field=models.CharField(blank=True, help_text='For security purposes. Their address when they verified.', max_length=2000, null=True),
        ),
    ]
