# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20180103_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('MEMBER', 'Member')], default='EDITOR', max_length=15),
        ),
    ]
