# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-18 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20190903_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
