# Generated by Django 2.2.8 on 2019-12-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_remove_supplieremailnotification_supplier'),
        ('company', '0102_remove_collaborationinvite_requestor'),
        ('supplier', '0009_auto_20191121_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
