# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aims', django.contrib.postgres.fields.jsonb.JSONField(help_text='list of strings e.g., ["AIM1", "AIM2"]')),
                ('company_number', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('personal_name', models.CharField(max_length=100)),
                ('sqs_message_id', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
    ]
