# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-29 15:36
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrolment',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='enrolment',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
    ]
