# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-18 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='company_number',
            field=models.CharField(help_text='Companies House ID', max_length=8),
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='personal_name',
            field=models.CharField(max_length=255),
        ),
    ]
