# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-07 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0002_auto_20161129_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='sqs_message_id',
        ),
    ]
