# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-20 10:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0005_trustedsourcesignupcode'),
    ]
