# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0008_auto_20170627_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preverifiedenrolment',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
