# Generated by Django 2.2.7 on 2019-11-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0009_auto_20190313_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preverifiedenrolment',
            name='company_number',
            field=models.CharField(max_length=8),
        ),
    ]
