# Generated by Django 2.2.8 on 2020-02-20 14:51

import directory_validators.string
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0010_auto_20191121_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='preverifiedenrolment',
            name='company_name',
            field=models.TextField(blank=True, null=True, validators=[directory_validators.string.no_html]),
        ),
        migrations.AlterField(
            model_name='preverifiedenrolment',
            name='company_number',
            field=models.CharField(max_length=8, validators=[directory_validators.string.no_html]),
        ),
    ]
