# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name')),
                ('company_email', models.EmailField(max_length=254, unique=True, verbose_name='company email')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates whether the user has superuser privileges.', verbose_name='superuser status')),
                ('terms_agreed', models.BooleanField(default=False, verbose_name='terms_agreed')),
                ('referrer', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='referrer')),
                ('confirmation_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='confirmation code')),
                ('company_email_confirmed', models.BooleanField(default=False, help_text='Designates whether the user has confirmed company_email address.', verbose_name='company_email confirmed')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.Company')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
