# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-28 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_id', models.PositiveIntegerField(unique=True, verbose_name='sso user.sso_id')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name')),
                ('mobile_number', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=254, unique=True, verbose_name='company email')),
                ('company_email_confirmed', models.BooleanField(default=False, help_text='Designates whether the user has confirmed company_email address.', verbose_name='company email confirmed')),
                ('company_email_confirmation_code', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='company email confirmation code')),
                ('referrer', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='referrer')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('terms_agreed', models.BooleanField(default=False, verbose_name='terms_agreed')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.Company')),
            ],
        ),
    ]
