# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referrer',
            field=models.CharField(max_length=255, verbose_name='referrer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_agreed',
            field=models.BooleanField(default=False, verbose_name='terms_agreed'),
        ),
    ]
