# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-24 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
