# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-17 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20161017_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referrer',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='referrer'),
        ),
    ]
