# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-11-08 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20161206_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='terms_agreed',
        )
    ]
