# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20161206_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created', '-modified')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_email_confirmation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_email_confirmed',
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='company.Company'),
        ),
    ]
