# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170112_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unsubscribed',
            field=models.BooleanField(default=False, help_text='Designates whether this user should receive notifications', verbose_name='unsubscribed'),
        ),
    ]
