# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-06 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_unsubscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_company_owner',
            field=models.BooleanField(default=False),
        ),
    ]
