# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-07 15:52
from __future__ import unicode_literals

from django.db import migrations


def set_company_owner(apps, schema_editor):
    User = apps.get_model("user", "User")
    User.objects.all().update(is_company_owner=True)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_company_owner'),
    ]

    operations = [
        migrations.RunPython(set_company_owner, migrations.RunPython.noop),
    ]



