# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20170907_1552'),
        ('supplier', '0002_auto_20180103_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='company.Company'),
        ),
    ]
