# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180103_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
