# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 11:46
from __future__ import unicode_literals

from django.db import migrations
from directory_constants import user_roles

class Migration(migrations.Migration):

    def populate_user_roles(apps, schema_editor):
        User = apps.get_model('user', 'User')
        for user in User.objects.all():
            if user.is_company_owner:
                user.role = user_roles.ADMIN
            else:
                user.role = user_roles.EDITOR
            user.save()

    dependencies = [
        ('user', '0012_user_role'),
    ]

    operations = [
        migrations.RunPython(
            populate_user_roles, migrations.RunPython.noop
        ),
    ]
