# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-09 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190809_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_company_owner',
        ),
    ]
