# Generated by Django 3.2.16 on 2022-12-05 15:44

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('RADIO', 'radio'), ('SELECT', 'select'), ('MULTI_SELECT', 'multi_select'), ('TEXT', 'text')], max_length=255)),
                ('add_other_option', models.BooleanField(default=False, help_text='If selected, will display an option for users to enter a choice not listed.', verbose_name="Add 'other' option")),
                ('order', models.IntegerField(help_text='The order in which the question appears in the survey.')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('label', models.CharField(help_text='The text that will appear to users when the form is displayed', max_length=255, unique=True)),
                ('value', models.CharField(help_text='The value that the choice will be saved as if a user selects it', max_length=255, unique=True)),
                ('jump', models.ForeignKey(blank=True, help_text='The question that the user will be shown next if they select thischoice,\n         if left blank they will be taken to the next question in order', null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
