# Generated by Django 3.2.16 on 2023-01-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_choice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('radio', 'Radio'), ('select', 'Select'), ('multi_select', 'Multi select'), ('short_text', 'Short text'), ('long_text', 'Long text')], max_length=255),
        ),
    ]
