# Generated by Django 3.2.16 on 2023-01-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='jump',
        ),
        migrations.AddField(
            model_name='choice',
            name='additional_routing',
            field=models.CharField(blank=True, choices=[('end', 'Go to end'), (None, 'None, go to next question'), ('jump', 'Jump to a different question')], default=None, help_text='If a user selects this choice, is there any additional routing? Or do they go to the next question in order.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='question_to_jump_to',
            field=models.ForeignKey(blank=True, help_text="The question that the user will be shown next if they select this choice. \n        This field is mandatory if additional routing is set to 'Jump to different question'.", null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question'),
        ),
    ]
