# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='office',
            name='phone_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='phone_other_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
