# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 11:50
from __future__ import unicode_literals

from django.db import migrations


def create_offices(apps, schema_editor):
    Office = apps.get_model('exporting', 'Office')
    Office.objects.bulk_create([
        Office(
            region_id='yorkshire_and_the_humber',
            name='DIT Yorkshire and the Humber',
            address_street='County Way',
            address_city='Barnsley',
            address_postcode='S70 2JW',
            email='yorkshire@mobile.trade.gov.uk',
            phone='0300 365 1000',
        ),
        Office(
            region_id='north_west',
            name='DIT North West',
            address_street='Lee House, 90 Great Bridgewater Street',
            address_city='Manchester',
            address_postcode='M1 5JW',
            email='info@tradenw.org',
            phone='0333 320 0392',
        ),
        Office(
            region_id='wales',
            name='Business Wales',
            address_street='Welsh Government',
            address_city='Sarn Mynach, Llandudno Junction',
            address_postcode='LL31 9RZ',
            email='businesssupport@wales.gsi.gov.uk',
            phone='0300 060 3000',
            website='http://www.business.wales.gov.uk/zones/export',
        ),
        Office(
            region_id='east_midlands',
            name='DIT East Midlands',
            address_street='The International Trade Centre, 5 Merus Court, Meridian Business Park',
            address_city='Leicester',
            address_postcode='LE19 1RJ',
            email='info@tradeEM.co.uk',
            phone='0345 052 4001',
        ),
        Office(
            region_id='east_of_england',
            name='DIT East of England',
            address_street='Titan Court, 3 Bishops Square',
            address_city='Hatfield, Hertfordshire',
            address_postcode='AL10 9NE',
            email='eastinfo@mobile.trade.gov.uk',
            phone='01707 398 398',
        ),
        Office(
            region_id='south_east',
            name='DIT South East',
            address_street='Unit 10, Fulcrum, 2 Solent Way',
            address_city='Fareham',
            address_postcode='PO15 7FN',
            email='info@tradesoutheast.com',
            phone='0330 300 0012',
        ),
        Office(
            region_id='scotland',
            name='Scottish Enterprise',
            address_street='Atrium Court, 50 Waterloo Street',
            address_city='Glasgow',
            address_postcode='G2 6HQ',
            email='international@scotent.co.uk',
            phone='0300 013 3542',
            phone_other='0141 247 1385',
            phone_other_comment='from mobile phones or if outside Scotland',
            website='https://www.scottish-enterprise.com/international'
        ),
        Office(
            region_id='south_west',
            name='DIT South West',
            address_street='Leigh Court, Abbots Leigh',
            address_city='Bristol',
            address_postcode='BS8 3RA',
            email='DITsw@mobile.trade.gov.uk',
            phone='01275 370 944',
        ),
        Office(
            region_id='london',
            name='DIT London',
            address_street='6th Floor, 140 Aldersgate Street',
            address_city='London',
            address_postcode='EC1A 4HY',
            email='export@tradelondon.org.uk',
            phone='020 7234 3000',
        ),
        Office(
            region_id='northern_ireland',
            name='Invest NI',
            address_street='Bedford Square, Bedford Street',
            address_city='Belfast',
            address_postcode='BT2 7ES',
            email='enquiry@investni.com',
            phone='0800 181 4422',
            website='https://www.investni.com',
        ),
        Office(
            region_id='north_east',
            name='DIT North East',
            address_street='Aykley Heads Business Centre',
            address_city='Durham',
            address_postcode='DH1 5TS',
            email='northeast@mobile.trade.gov.uk',
            phone='0345 136 0169',
        ),
        Office(
            region_id='west_midlands',
            name='DIT West Midlands',
            address_street='75 Harborne Road',
            address_city='Birmingham',
            address_postcode='B15 3DH',
            email='wmenquiries@mobile.trade.gov.uk',
            phone='0345 222 0159',
        ),

    ])


class Migration(migrations.Migration):

    dependencies = [
        ('exporting', '0002_auto_20181121_1223'),
    ]

    operations = [
        migrations.RunPython(create_offices, migrations.RunPython.noop),
    ]
