# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-26 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exporting', '0003_auto_20181121_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['region_id']},
        ),
    ]
