# Generated by Django 2.2.24 on 2021-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporting', '0004_auto_20181126_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='override_office_details',
            field=models.TextField(blank=True,
                                   help_text='If this field has a value all fields above will be ignored and the details in this field will be displayed. Other office details will not be displayed if this is the main search result. If this office is in the results page of other offices, this will be the details displayed.',
                                   null=True),

        ),
    ]
