# Generated by Django 2.2.28 on 2022-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporting', '0005_override_office_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='region_id',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='office',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
