# Generated by Django 3.2.16 on 2023-03-08 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exporting', '0006_auto_20220613_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='region_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Regions need to be separated by commas.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='office',
            name='address_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='address_postcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='address_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='region_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
