# Generated by Django 2.2.8 on 2020-02-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='city',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
