# Generated by Django 2.2.13 on 2020-11-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personalisation', '0004_suggestedcountry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestedCountry',
        ),
    ]
