# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-24 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_buyeremailnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeremailnotification',
            name='category',
            field=models.CharField(choices=[('new_companies_in_sector', 'New companies in sector')], max_length=255),
        ),
        migrations.AlterField(
            model_name='supplieremailnotification',
            name='category',
            field=models.CharField(choices=[('no_case_studies', 'Case studies not created'), ('hasnt_logged_in', 'Not logged in after first 30 days'), ('verification_code_not_given', 'Verification code not supplied'), ('verification_code_2nd_email', 'Verification code not supplied - 2nd email')], max_length=255),
        ),
    ]
