# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-07 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20170224_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUnsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
