# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-09 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_anonymousunsubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousEmailNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('new_companies_in_sector', 'New companies in sector')], max_length=255)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='buyeremailnotification',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='BuyerEmailNotification',
        ),
    ]
