# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-10 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20170309_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousemailnotification',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
