# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_supplieremailnotification_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieremailnotification',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.CompanyUser'),
        ),
        migrations.AlterField(
            model_name='supplieremailnotification',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier'),
        ),
    ]
