# Generated by Django 2.2.7 on 2019-11-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_supplieremailnotification_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieremailnotification',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='company.CompanyUser'),
        ),
        migrations.AlterField(
            model_name='supplieremailnotification',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, to='supplier.Supplier'),
        ),
    ]
