# Generated by Django 2.2.8 on 2019-12-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20191121_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieremailnotification',
            name='supplier',
        ),
    ]
