# Generated by Django 2.2.8 on 2020-02-04 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_remove_supplieremailnotification_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplieremailnotification',
            name='company_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.CompanyUser'),
        ),
    ]
