# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-27 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True)),
                ('source_url', models.CharField(max_length=200, blank=True, null=True)),
                ('target_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
